### ISSUE TITLE
Browser compatibility

### ISSUE THREAD

**Issue by eah13** [astro-pi/beta-testing#1]
A list of supported browsers and known issues is below.  If you think you've encountered a problem, please either comment here or open a new issue with as much information about versions and how to reproduce the bug as you can. Thanks!

Full support:
- Chrome
- Firefox
- Safari
- Edge (with non-fancy solid color LEDs rather than our normal RGB opacity based blending)
- Internet Explorer 10+

Turned off enhanced code editor features like syntax highlighting and autocomplete:
- Epiphany
- Midori
- Iceweasel

Code Downloads not supported (working on this):
- Midori
- Epiphany

**Comment by eah13** [comment]
Per #10 everything seems in order on Edge.

**Comment by ukscone** [comment]
colours for the emulated leds is a bit off on Edge on Win10
![coloursoffinedge](https://cloud.githubusercontent.com/assets/3171454/16875452/8464da2e-4a6d-11e6-96fd-37c16bdba756.PNG)

**Comment by eah13** [comment]
@ukscone thanks for reporting this.  [Looks like we'll need a workaround for Edge](http://caniuse.com/#feat=css-mixblendmode) on this display issue.  In your opinion is the current state usable or is a fix needed to use the emulator in Edge?

**Comment by eah13** [comment]
Answered my own question when I tested on edge.  Definitely unusable.  Workaround on the way.

**Comment by eah13** [comment]
@ukscone @TeCoEd and anyone else who saw strange colors in Edge, a fix is now pushed!  if you don't see the change, make sure you hard refresh with `Ctrl-F5`

This isn't identical to what you'll see on Chrome since the Edge team has chosen to not fully support modern web standards like, say, CSS.  But still pretty usable.

![capture](https://cloud.githubusercontent.com/assets/1702745/16886182/b7484b78-4aa0-11e6-8ec8-e24ad77d5751.PNG)

**Comment by ukscone** [comment]
looks pretty good in edge from trying  a few of the demos

**Comment by eah13** [comment]
Epiphany and midori are now supported!

**Comment by eah13** [comment]
Updated issue to be full list of supported browsers and known issues
