### ISSUE TITLE
LED quantization

### ISSUE THREAD

**Issue by waveform80** [astro-pi/beta-testing#13]
The sense HAT's pixel frame-buffer stores data in RGB565 format, and the official sense HAT library leaves the lower bits blank when converting back from RGB565 to RGB888. Given the following code:

``` python
from sense_hat import SenseHat
import time

sense = SenseHat()

sense.set_pixel(0, 0, 255, 255, 255)
print(sense.get_pixel(0, 0))
```

A real sense HAT produces the result:

```
[248, 252, 248]
```

Due to the reduction of the 8-bit values to 5, 6, and 5 bits respectively (without the typical correction of the low bits; it's also worth noting the actual hardware performs a further refinement to RGB555 and then uses the gamma lookup table to produce the final colours).

However, the current emulation produces the following result:

```
[255, 255, 255]
```

Which is indeed the input, but not what the code will produce on the actual hardware.

**Comment by eah13** [comment]
Thanks for reporting.  Looks like we'll need to tweak the pixel math in our version of the module.

**Comment by eah13** [comment]
This is fixed!  A separate bug we discovered is that get_pixel doesn't read from the current state of the LEDs that were set by a past program, instead returning (0,0,0) since we don't preserve that state between runs in our logic.  Working on a fix for that...
