### ISSUE TITLE
Keyboard control of joystick tool tip?

### ISSUE THREAD

**Issue by davidhoness** [astro-pi/beta-testing#14]
I was wondering if we should have a way to let users know about using the cursor keys and Enter for the joystick?

Perhaps detect clicks on that area of the screen or mouse hover etc, and then display a pop out or a tool tip? I think this would be helpful for more casual users who won't read the documentation.

**Comment by ukscone** [comment]
it did take me a while to workout that clicking the joystick with the mouse did diddily squat. there's documentation? where?

**Comment by davidhoness** [comment]
I don't think there is any online yet.

**Comment by eah13** [comment]
Thanks for the feedback on this.  We're going to experiment with a modal or infobutton of some sort as a first step. We may also be able to display a contextual help message if someone clicks on the joystick. Long term, we'd love to be able to support manipulating the joystick directly with mouse and/or touch.

**Comment by eah13** [comment]
This is now deployed!  There is now an `i` icon in the lower right of the display that shows this text when clicked:

![screenshot 2016-07-25 at 1 19 20 pm](https://cloud.githubusercontent.com/assets/1702745/17110326/734005de-526a-11e6-8454-165a0ab45e30.png)

We wanted it to be unobtrusive but easily learnable.  

Feedback welcome.  I'll close this as fixed but please drop any feedback here that we can incorporate in any revisions.
