### ISSUE TITLE
Off vs White LED colour contrast

### ISSUE THREAD

**Issue by davidhoness** [astro-pi/beta-testing#16]
I've noticed on Epiphany, but it may also occur on other browsers, a lack of contrast between white LEDs and ones that are turned off. Screen shot from Epiphany below;

![2016-07-20-084810_1920x1080_scrot](https://cloud.githubusercontent.com/assets/6640424/16980814/b8917eec-4e5f-11e6-9aec-8448c96e10b9.png)

And here's one from Fire Fox on Ubuntu.

![screenshot from 2016-07-20 09 47 56](https://cloud.githubusercontent.com/assets/6640424/16980883/0cfe5b1c-4e60-11e6-8895-e17c61c84e0f.png)

**Comment by grega** [comment]
The same contrast issue is present on Firefox 47 (Mac):

<img width="1319" alt="firefox" src="https://cloud.githubusercontent.com/assets/91799/16988632/f381c6d2-4e88-11e6-88f8-6005b7353539.png">

vs. Chrome 51 (Mac):

<img width="1356" alt="chrome" src="https://cloud.githubusercontent.com/assets/91799/16988641/fb08e200-4e88-11e6-9ffb-354809f51406.png">

**Comment by davidhoness** [comment]
I'm wondering if this is to do with the Edge-style SVG rendering fix that went into the last build.

**Comment by eah13** [comment]
Looking in to this.  It's not related to the Edge-style SVG rendering per se but rather browsers not rendering the SVG's off-state correctly (there's transparency in the offstate that gets combined incorrectly).  If we can test for lack of support for the rendering we use we could insert a darker fallback fill as the LED offstate for those machines.  

That said, I'm very surprised that Firefox 47 for Mac is showing this behavior- will grab a mac and investigate.

**Comment by eah13** [comment]
This should be fixed!  While I was in there I cleaned everything up, darkened the offstate for all browsers and fine-tuned the SVG.  

Before (Chrome):
![screenshot 2016-07-26 at 3 33 45 pm](https://cloud.githubusercontent.com/assets/1702745/17221236/04e65d64-54c1-11e6-9f42-5aa304b89099.png)

After (Chrome):
![screenshot 2016-07-26 at 3 35 21 pm](https://cloud.githubusercontent.com/assets/1702745/17221245/0ac7ce16-54c1-11e6-8904-63ae45d3f693.png)

Special thanks to @grega for the Firefox screenshot.  I wasn't able to replicate in FF, but I did figure out that that screenshot could be reproduced by ignoring the opacities of some elements so I rewrote it to not use opacity at all in the offstate.  This may speed things up a tiny bit in Epiphany too.

Definitely an improvement, so thanks again for the suggestions!  The colors really pop on the new darker background.  Give it a look and let me know what you think.  

Closing for now.  If there are any other problems related to this after a refresh please comment here.
