### ISSUE TITLE
Rotate virtual Sense HAT

### ISSUE THREAD

**Issue by davidhoness** [astro-pi/beta-testing#17]
Feature request. I keep finding I want to change the angle of the virtual Sense HAT (by multiples of 90). I think this would be a fairly simple feature to add and would allow users to explore the issues that occur when the Sense HAT is not held in the default orientation.

For example, if inverted by 180 the joystick keys don't automatically change and they would need to accommodate for this in their code. Up becomes down and left becomes right etc. They would also need to set the LED matrix to the correct rotation angle.

We could also, perhaps, show an Astro Pi icon to indicate when the Sense HAT is in the Astro Pi flight orientation. A nice visual indication like that would then let students know to select it if they're planning to submit their code to a competition.

**Comment by eah13** [comment]
Good thought.  One complexity of shifting the orientation would be what to do about the keyboard presses.  I'm assuming if the sensehat were rotated like it is in the Astro Pi that pressing the up key would move the joystick 'up' relative to me, which would be the device's left direction.  Maybe that will be clear to users but something we'll need to pay attention to when we get there.

If I'd thought of this earlier I'd have suggested the joystick to be responsive to rotation (even if only optionally) in the recent API changes.

**Comment by davidhoness** [comment]
Yeah it would a nice API enhancement for the main library. Currently though the key events are fixed and remain the same regardless of orientation. All the Astro Pi flight code uses the screen rotated to 270 (or rotated 90 degrees left) and the joystick like so:

| Relative direction | Key event |
| --- | --- |
| Up | Left |
| Down | Right |
| Left | Down |
| Right | Up |

So my preference is that the emulator should also present this problem to the user so that they can make their code accommodate it, and thus it will work correctly on an Astro Pi flight unit.

**Comment by waveform80** [comment]
Hmm, interesting enhancement. I could add a `rotate` property to the SenseStick class which accepts 0, 90, 180, 270 like the main class, then update the main class' `set_rotation` method to update the embedded SenseStick.

**Comment by davidhoness** [comment]
@waveform80 That would be the way to do it for certain. Let's keep this in reserve, I want to keep the main library frozen for the time being.

**Comment by waveform80** [comment]
Okay, no prob.

**Comment by davidhoness** [comment]
@eah13: Is there any chance this could go if for release? Let me know if it's not as simple to do as I think it is. Maybe it screws up how the SVG is addressed or something?

**Comment by eah13** [comment]
@davidhoness definitely possible.  I sent you an email to discuss and perhaps we can hop on for a quick chat about this to make sure we've got the details right.

**Comment by eah13** [comment]
Implemented!  Thanks again for the idea.
![screenshot 2016-08-02 at 9 58 35 am](https://cloud.githubusercontent.com/assets/1702745/17331151/b9086b46-5897-11e6-8308-5fba343bb219.png)

I opened #26 to keep track of feedback on the feature.
