### ISSUE TITLE
Ready for testing: rotation button

### ISSUE THREAD

**Issue by eah13** [astro-pi/beta-testing#26]
(Thanks to an idea from @davidhoness) we've added a rotation button that allows the user to rotate how the Sense HAT is displayed.  This is independent from `set_rotation`, like the sensor values, but is intended to facilitate writing programs in non-standard orientations.  Like the sensor values, the rotation of the Sense HAT is remembered when sharing or saving a trinket.

Example of a Sense HAT turned 90 degrees:
![screenshot 2016-08-02 at 9 58 35 am](https://cloud.githubusercontent.com/assets/1702745/17331270/2fd0bf58-5898-11e6-9751-0f4c79b81107.png)

**Comment by davidhoness** [comment]
I think I've found a bug where the rotational sequence isn't correct after loading a saved trinket;
https://trinket.io/python/270526d02f (set to 180 deg)
You have to click a joystick key for the message to scroll.

It should go: 0, 90, 180, 270, back to 0 - however, after loading the above trinket clicking on the rotation button should go to 270, but it goes to 90 - but is showing the SVG at 270. I guess this is just the label for the button?

**Comment by davidhoness** [comment]
I've also noticed if I stop (while running) the above trinket and run it again, the rotation resets to zero. It seems to continue to the next rotational position if I click rotate again after this. So say you're on 270, click run and it resets to zero, click rotate again and it animates rotating from 270 to zero.

**Comment by davidhoness** [comment]
I am also seeing an issue where I lose the ability to get keyboard focus onto the hidden input for the joystick. I've seen it in both Chrome and Fire Fox. After loading a trinket and running it, I rotate it all the way around a few times and then I can't get the focus onto the joystick while the code is running.

I think this may have something to do with allowing the program to end, and the joystick only being movable while the code is running.

Yes, I think I can reproduce it. So the above trinket, run it - let it run to completion. Note the joystick doesn't move while the code isn't running. Run the trinket again and you can't get focus on the joystick. Reproduced on Chrome 51.0.2704.103m under Windows 10 and on Fire Fox 47.0 on Ubuntu 14.04.

**Comment by davidhoness** [comment]
@eah13 should I raise these as separate issues? Hopefully these aren't too hard to solve, otherwise I think we might have to release without this feature.

**Comment by eah13** [comment]
No, this is a great place for that.  Looking into these.

**Comment by eah13** [comment]
@davidhoness thanks for the detailed report- this is fixed now!

**Comment by davidhoness** [comment]
You guys rock. Fixes verified in Chrome and FF!
