### ISSUE TITLE
Possible for joystick to disappear

### ISSUE THREAD

**Issue by davidhoness** [astro-pi/beta-testing#27]
I found another very minor cosmetic issue which may only occur in rare circumstances.
If you're holding down a joystick key when the program ends, the joystick will disappear when you next run the code. Note, it does come back when you press a key.

![screenshot from 2016-08-03 09 16 01](https://cloud.githubusercontent.com/assets/6640424/17358652/f7846a8c-595a-11e6-943e-5b14ad64cf69.png)

I guess it's an SVG layer thing?

**Comment by eah13** [comment]
Thanks for reporting!  This is now fixed, and we now use relative directions when the joystick is rotated.
