### ISSUE TITLE
Space Invader demo doesn't load

### ISSUE THREAD

**Issue by topshed** [astro-pi/beta-testing#4]
Produces the following error:

IOError: Failed to load URL: https://trinket.io/embed/space_invader.png on line 418 in src/lib/sense_hat/hat.py

Chrome Version 51.0.2704.103 (64-bit) on OSX 10.11.3

**Comment by brianpmarks** [comment]
Thanks for the report. I believe the space invader demo should load now.

**Comment by TeCoEd** [comment]
Tested and yes it works

**Comment by eah13** [comment]
Another bug bites the dust
