### ISSUE TITLE
Joystick doesn't work in any examples

### ISSUE THREAD

**Issue by topshed** [astro-pi/beta-testing#5]
Can't seem to make joystick work. Clicking on it does nothing - has no effect.

Version 51.0.2704.103 (64-bit) on OSX 10.11.3

**Comment by brianpmarks** [comment]
Thanks for the report.

Does the joystick work for you if you use the arrow keys on your keyboard just after running code?

**Comment by davidhoness** [comment]
I'm also still seeing the joystick focus problem on FireFox. When I press the cursor keys the window scrolls instead of the stick moving.

FireFox 47.0, Mozilla Firefox for Ubuntu canonical - 1.0.
Linux 3.13.0-91-generic #138-Ubuntu SMP Fri Jun 24 17:00:34 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by brianpmarks** [comment]
Thanks for the update. I'll be looking into this one today.

**Comment by eah13** [comment]
I'm able to reproduce this in Chrome:
- In incognito, open a page.  Joystick won't focus.  

Workaround:
- Hard refresh (Shift-Ctrl/Cmd-R).  Joystick works now and for subsequent pages.

@davidhoness @topshed If the workaround above resolves this for you please use it to continue testing.  We'll work on a resolution and post the results here.  Thanks!

**Comment by brianpmarks** [comment]
@davidhoness @topshed I just made some updates to how we listen for Joystick events. When you get a chance try the examples again and let me know how it goes.

**Comment by eah13** [comment]
I'm no longer able to reproduce.  We'll close this tomorrow unless anyone has the problem persisting.

**Comment by eah13** [comment]
Joysticks are a go
