### ISSUE TITLE
Shared projects do not retain uploaded images

### ISSUE THREAD

**Issue by davidhoness** [astro-pi/beta-testing#6]
Project code: 62c0b0fc5c (I haven't put the full link for obvious reasons)

The two images I uploaded for this project are missing when I open the shareable link in a new browser window. Possibly related to #4 

IOError: Failed to load URL: https://trinket.io/embed/python/mp3_1.png on line 418 in src/lib/sense_hat/hat.py

**Comment by brianpmarks** [comment]
Thanks for the report. As far as I can tell this happens the first time you visit the link but if you click run again it worked for me. Will check this out today.

**Comment by brianpmarks** [comment]
@davidhoness: Give this one another try when you get a chance if you don't mind. I think I've got it working now.

**Comment by davidhoness** [comment]
Yep, that's now working for me. Thank you!

**Comment by eah13** [comment]
Excellent!  Closing.
