### ISSUE TITLE
random_sparkles.py is slow/hangs

### ISSUE THREAD

**Issue by TeCoEd** [astro-pi/beta-testing#7]
Loads code after about 2 minutes, then using a while loop it never runs and stalls.  May be the Internet speed? 
Using Chrome on Win10

**Comment by eah13** [comment]
Hmm. If you open an incognito window to the demo page and load the sparkles page and run it does if happen for you then?

If not, what was the program that you were running directly before sparkles, do you remember?  Sounds like your browser may have been busy, so we should look into that other program. 

(Thanks for reporting!)

**Comment by TeCoEd** [comment]
Hi, I ran Sparkles from a fresh browser tab and it still stalled.

**Comment by eah13** [comment]
On Windows 10 Chrome 51.0.2704.106 the only way I can reproduce a hang is by deleting the sleep statement, making me think this may be an instance of #12. I'll close this and we'll track this there.  If anyone else is able to reproduce on Windows Chrome please post here and we'll reopen.
