### ISSUE TITLE
Running in Console

### ISSUE THREAD

**Issue by TeCoEd** [astro-pi/beta-testing#9]
If you load a program and press Console instead of Run the program produces errors and stalls, have to reload the site and link.
Chrome Win10

**Comment by eah13** [comment]
Reproduced on ChromeOS as well!  Thanks.  We tinkered with Console mode recently and must've left a bug accidentally.

**Comment by eah13** [comment]
This is fixed!  Console mode should now work as expected with the sense_hat module.
